build: nginx https 설정

diff --git a/docker-compose.aws.yml b/docker-compose.aws.yml
--- a/docker-compose.aws.yml
+++ b/docker-compose.aws.yml
@@ -4,11 +4,52 @@ services:
     container_name: kx-nginx
     depends_on:
       - app
+    env_file:
+      - ${APP_ENV_FILE:-.env}
     ports:
       - "80:80"
+      - "443:443"
+    command: >
+      /bin/sh -c "
+      if [ -f /etc/letsencrypt/live/$$CERTBOT_DOMAIN/fullchain.pem ] &&
+         [ -f /etc/letsencrypt/live/$$CERTBOT_DOMAIN/privkey.pem ]; then
+        envsubst '$$CERTBOT_DOMAIN' < /etc/nginx/templates/https.conf.template > /etc/nginx/conf.d/default.conf;
+      else
+        envsubst '$$CERTBOT_DOMAIN' < /etc/nginx/templates/http.conf.template > /etc/nginx/conf.d/default.conf;
+      fi;
+      nginx -g 'daemon off;'
+      "
     volumes:
-      - ./nginx/conf.d:/etc/nginx/conf.d:ro
+      - ./nginx/templates:/etc/nginx/templates:ro
+      - ./certbot/conf:/etc/letsencrypt
+      - ./certbot/www:/var/www/certbot
     restart: unless-stopped
+
+  certbot:
+    image: certbot/certbot
+    container_name: kx-certbot
+    profiles:
+      - certbot
+    env_file:
+      - ${APP_ENV_FILE:-.env}
+    volumes:
+      - ./certbot/conf:/etc/letsencrypt
+      - ./certbot/www:/var/www/certbot
+    entrypoint: /bin/sh
+    command: >
+      -c "
+      test -n "$$CERTBOT_DOMAIN" || { echo 'CERTBOT_DOMAIN is required'; exit 1; };
+      test -n "$$CERTBOT_EMAIL" || { echo 'CERTBOT_EMAIL is required'; exit 1; };
+      certbot certonly
+      --non-interactive
+      --webroot
+      --webroot-path /var/www/certbot
+      --email "$$CERTBOT_EMAIL"
+      --agree-tos
+      --no-eff-email
+      --keep-until-expiring
+      -d "$$CERTBOT_DOMAIN"
+      "
 
   app:
     image: ${DOCKER_IMAGE}
